using System.Collections.Generic;

namespace Anaximander.Linq
{
    /// <summary>
    /// A collection of sub-collections, generated by using a selector to partition the source collection.
    /// </summary>
    public interface IBoxedEnumerable<out T> : IEnumerable<IEnumerable<T>>
    {
    }
}